@host = http://localhost:9999
@apiVersion = 1

POST {{host}}/api/v{{apiVersion}}/games
Accept: application/json
Content-Type: application/json

{
    "playersId": [
        "01d28759-42fb-4503-8a28-f5c96345aa6e",
        "cbd44723-56fb-464c-99a3-5a6894c7ef33"
    ]
}
