@host = http://localhost:5173
@apiVersion = 1

POST {{host}}/api/v{{apiVersion}}/games
Accept: application/json
Content-Type: application/json

{
    "playersId": [
        "033406b0-e3bd-40c5-a978-448f0b058bd8",
        "5436e1db-afe0-488f-ad5f-02380ea87dea"
    ]
}
